title: all to know
remote_theme: just-the-docs/just-the-docs
color_scheme: light
nav_sort: case_insensitive

navigation:
  - title: Home
    url: /
  - title: Business
    url: /business.html
  - title: Economics
    url: /economics.html
  - title: Finance
    url: /finance.html
